# Site settings
title: ZBT Albany
email: albanyzbtvicepresident@gmail.com
description: ZBT 
url: http://albanyzbtvicepresident.github.io
github_username: albanyzbtvicepresident

# Build settings
markdown: kramdown
